
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author emree
 */
public class SiparisUygulamasi extends javax.swing.JFrame {
    
    private Map<String, Integer> map = new LinkedHashMap<>();

    /**
     * Creates new form SiparisUygulamasi
     */
    public SiparisUygulamasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        iskender = new javax.swing.JCheckBox();
        beyti = new javax.swing.JCheckBox();
        ssk = new javax.swing.JCheckBox();
        ayran = new javax.swing.JCheckBox();
        salgam = new javax.swing.JCheckBox();
        siparisleriGoster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Siparis Uygulamasi");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menü");

        iskender.setText("İskender - 220 TL");

        beyti.setText("Beyti - 180 TL");
        beyti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beytiActionPerformed(evt);
            }
        });

        ssk.setText("SSK - 200 TL");

        ayran.setText("Ayran - 25 TL");

        salgam.setText("Şalgam - 30 TL");

        siparisleriGoster.setText("Siparisleri Goster");
        siparisleriGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siparisleriGosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salgam)
                    .addComponent(ayran)
                    .addComponent(ssk)
                    .addComponent(beyti)
                    .addComponent(iskender)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(siparisleriGoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(iskender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(beyti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ssk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ayran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salgam)
                .addGap(18, 18, 18)
                .addComponent(siparisleriGoster)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beytiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beytiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beytiActionPerformed
    
    public void urunleriGoster(){
        int toplam = 0;
        String message = "";
        
        if(!map.isEmpty()){
            message += "Fatura:\n";
            for(Map.Entry<String, Integer> entry : map.entrySet()){
                toplam += entry.getValue();
                message += entry.getKey() + " - " + entry.getValue()+ " TL\n";
            }
            message += "Toplam : " + toplam;
        }else{
            message = "Siparisiniz bulunmamaktadir!";
        }
        
        
        
        JOptionPane.showMessageDialog(this, message);
    }
    
    private void siparisleriGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siparisleriGosterActionPerformed
        // TODO add your handling code here:
        if(iskender.isSelected()){
            map.put("İskender",220);
        }else{
            map.remove("İskender");
        }
        if(beyti.isSelected()){
            map.put("Beyti",180);
        }else{
            map.remove("Beyti");
        }
        if(ssk.isSelected()){
            map.put("SSK",200);
        }else{
            map.remove("SSK");
        }
        if(ayran.isSelected()){
            map.put("Ayran",25);
        }else{
            map.remove("Ayran");
        }
        if(salgam.isSelected()){
            map.put("Salgam",30);
        }else{
            map.remove("Salgam");
        }
        urunleriGoster();
        iskender.setSelected(false);
        beyti.setSelected(false);
        ssk.setSelected(false);
        ayran.setSelected(false);
        salgam.setSelected(false);
        
    }//GEN-LAST:event_siparisleriGosterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparisUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ayran;
    private javax.swing.JCheckBox beyti;
    private javax.swing.JCheckBox iskender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox salgam;
    private javax.swing.JButton siparisleriGoster;
    private javax.swing.JCheckBox ssk;
    // End of variables declaration//GEN-END:variables
}
