
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author emree
 */
public class StokUygulamasi extends javax.swing.JFrame {

    /**
     * Creates new form StokUygulamasi
     */
    public StokUygulamasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        urunIsmiAlani = new javax.swing.JTextField();
        kategoriCB = new javax.swing.JComboBox<>();
        fiyatAlani = new javax.swing.JTextField();
        mesajYazisi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        urunTablosu = new javax.swing.JTable();
        urunEkleButon = new javax.swing.JButton();
        guncelleButon = new javax.swing.JButton();
        silButonu = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ürün İsmi :");

        jLabel3.setText("Kategori :");

        jLabel4.setText("Fiyat :");

        urunIsmiAlani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunIsmiAlaniActionPerformed(evt);
            }
        });

        kategoriCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kültür Sanat", "Yemek", "Elektronik", " " }));

        mesajYazisi.setForeground(new java.awt.Color(255, 0, 51));
        mesajYazisi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        urunTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün İsmi", "Kategori", "Fiyat"
            }
        ));
        urunTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urunTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urunTablosu);

        urunEkleButon.setText("Ürün Ekle");
        urunEkleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunEkleButonActionPerformed(evt);
            }
        });

        guncelleButon.setText("Ürünü Güncelle");
        guncelleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleButonActionPerformed(evt);
            }
        });

        silButonu.setText("Ürünü Sil");
        silButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silButonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(urunIsmiAlani)
                                    .addComponent(kategoriCB, 0, 166, Short.MAX_VALUE)
                                    .addComponent(fiyatAlani))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guncelleButon, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(urunEkleButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(silButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(urunIsmiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urunEkleButon))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kategoriCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guncelleButon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fiyatAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(silButonu)))
                .addGap(30, 30, 30)
                .addComponent(mesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urunIsmiAlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunIsmiAlaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urunIsmiAlaniActionPerformed

    private void urunEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunEkleButonActionPerformed
        // TODO add your handling code here:
        mesajYazisi.setText("");
        DefaultTableModel model = (DefaultTableModel) urunTablosu.getModel();
        mesajYazisi.setForeground(Color.red);
        if(urunIsmiAlani.getText().trim().isEmpty()){
            mesajYazisi.setText("Ürün ismi boş bırakılamaz!");
        }else{
            Object[] eklenecek = {urunIsmiAlani.getText(), kategoriCB.getSelectedItem().toString(),fiyatAlani.getText()};
            model.addRow(eklenecek);
            urunIsmiAlani.setText("");
            kategoriCB.setSelectedItem("Kültür Sanat");
            fiyatAlani.setText("");
            mesajYazisi.setForeground(Color.green);
            mesajYazisi.setText("Ürün başarıyla eklendi..");
        }
    }//GEN-LAST:event_urunEkleButonActionPerformed

    private void guncelleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleButonActionPerformed
        // TODO add your handling code here:
        mesajYazisi.setText("");
        DefaultTableModel model = (DefaultTableModel) urunTablosu.getModel();
        int seciliRow = urunTablosu.getSelectedRow();
        
        if(seciliRow == -1){ //tablo bossa ya da herhang bir yere tiklanmadiysa
            mesajYazisi.setForeground(Color.red);
            if(urunTablosu.getRowCount() == 0){
                mesajYazisi.setText("Tabloda ürün yok!");
            }else{
                mesajYazisi.setText("Güncellenecek sırayı seçiniz!");
            }   
        }else{
            model.setValueAt(urunIsmiAlani.getText(), seciliRow, 0);
            model.setValueAt(kategoriCB.getSelectedItem().toString(), seciliRow, 1);
            model.setValueAt(fiyatAlani.getText(), seciliRow, 2);
            mesajYazisi.setForeground(Color.green);
            mesajYazisi.setText("Ürün başarıyla güncellendi..");
           
        }
        
    }//GEN-LAST:event_guncelleButonActionPerformed

    private void urunTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urunTablosuMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) urunTablosu.getModel();
        
        int selectedRow = urunTablosu.getSelectedRow();
        
        urunIsmiAlani.setText(model.getValueAt(selectedRow, 0).toString());
        kategoriCB.setSelectedItem(model.getValueAt(selectedRow, 1));
        fiyatAlani.setText(model.getValueAt(selectedRow,2).toString());
    }//GEN-LAST:event_urunTablosuMouseClicked

    private void silButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silButonuActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) urunTablosu.getModel();
        
        int selectedRow = urunTablosu.getSelectedRow();
        
        if(selectedRow == -1){
            mesajYazisi.setForeground(Color.red);
            if(urunTablosu.getRowCount() == 0){
                mesajYazisi.setText("Tabloda ürün yok!");
            }else{
                mesajYazisi.setText("Silmek istediğiniz ürünü seçiniz!");
            }
        }else{
            model.removeRow(selectedRow);
            mesajYazisi.setForeground(Color.green);
            mesajYazisi.setText("Ürün başarıyla silindi..");
        }
    }//GEN-LAST:event_silButonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fiyatAlani;
    private javax.swing.JButton guncelleButon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kategoriCB;
    private javax.swing.JLabel mesajYazisi;
    private javax.swing.JButton silButonu;
    private javax.swing.JButton urunEkleButon;
    private javax.swing.JTextField urunIsmiAlani;
    private javax.swing.JTable urunTablosu;
    // End of variables declaration//GEN-END:variables
}
